---
Name: timednotices
After: 'rootroutes'
---
SilverStripe\Control\Director:
  rules:
   'timednotice//$Action/$ID/$OtherID': MBIE\TimedNotice\TimedNoticeController

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silverstripe-timednotices/javascript/timednotices-cms.js'
  extra_requirements_css:
    - 'silverstripe-timednotices/css/timednotices-cms.css'
