---
Name: timednotices
After: 'rootroutes'
---
SilverStripe\Control\Director:
  rules:
   'timednotice//$Action/$ID/$OtherID': SheaDawson\TimedNotice\TimedNoticeController

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'sheadawson/silverstripe-timednotices: javascript/timednotices-cms.js'
  extra_requirements_css:
    - 'sheadawson/silverstripe-timednotices: css/timednotices-cms.css'
